# VacationPy
----

#### Note
* Keep an eye on your API usage. Use https://developers.google.com/maps/reporting/gmp-reporting as reference for how to monitor your usage and billing.

* Instructions have been included for each segment. You do not have to follow them exactly, but they are included to help you think through the steps.

In [13]:
# Dependencies and Setup
import matplotlib.pyplot as plt
import pandas as pd
import numpy as np
import requests
import gmaps
import gmaps.datasets
import os
import json

# Import API key
from api_keys import g_key

### Store Part I results into DataFrame
* Load the csv exported in Part I to a DataFrame

In [14]:
weather_df = pd.read_csv('cities.csv')
weather_df.head()

,City_ID,City,Cloudiness,Country,Date,Humidity,Lat,Lng,Max Temp,Wind Speed
0,5354943.0,Half Moon Bay,1.0,US,10/15/20,33.0,37.46,-122.43,81.45,8.05
1,5983720.0,Iqaluit,90.0,CA,10/15/20,93.0,63.75,-68.51,37.20,4.70
2,3833367.0,Ushuaia,40.0,AR,10/15/20,77.0,-54.80,-68.30,59.00,11.41
3,2155415.0,New Norfolk,7.0,AU,10/15/20,74.0,-42.78,147.06,39.25,2.46
4,2411397.0,Georgetown,35.0,SH,10/15/20,77.0,-7.93,-14.42,73.09,15.43

In [15]:
weather_df = weather_df.dropna()

### Humidity Heatmap
* Configure gmaps.
* Use the Lat and Lng as locations and Humidity as the weight.
* Add Heatmap layer to map.

In [16]:
# Store latitude and longitude in locations
lat_lon = weather_df[['Lat', 'Lng']]

# Fill NaN values and convert to float
humid = weather_df["Humidity"].astype(float)
lat_lon.head()

     Lat     Lng
0  37.46 -122.43
1  63.75  -68.51
2 -54.80  -68.30
3 -42.78  147.06
4  -7.93  -14.42

In [17]:
# Plot Heatmap
figure_layout = {
    'width': '900px',
    'height': '600px',
    'border': '1px solid black',
    'padding': '1px',
    'margin': '0 auto 0 auto'
}

# Use the gmaps.figure passing a zoom_level of 2 and a center point so the map displays properly at
# a readable size
fig = gmaps.figure(layout=figure_layout,zoom_level=2,center=(15,25))
# Create heat layer
heat_layer = gmaps.heatmap_layer(lat_lon, weights=humid, 
                                 dissipating=False, max_intensity=100,
                                 point_radius=1.5)

# Add heat layer
fig.add_layer(heat_layer)

# Display figure
fig

Figure(layout=FigureLayout(border='1px solid black', height='600px', margin='0 auto 0 auto', padding='1px', wi…

### Create new DataFrame fitting weather criteria
* Narrow down the cities to fit weather conditions.
* Drop any rows will null values.

In [6]:
weather_df = weather_df.dropna()
weather_df.head()

,City_ID,City,Cloudiness,Country,Date,Humidity,Lat,Lng,Max Temp,Wind Speed
0,5354943.0,Half Moon Bay,1.0,US,10/15/20,33.0,37.46,-122.43,81.45,8.05
1,5983720.0,Iqaluit,90.0,CA,10/15/20,93.0,63.75,-68.51,37.20,4.70
2,3833367.0,Ushuaia,40.0,AR,10/15/20,77.0,-54.80,-68.30,59.00,11.41
3,2155415.0,New Norfolk,7.0,AU,10/15/20,74.0,-42.78,147.06,39.25,2.46
4,2411397.0,Georgetown,35.0,SH,10/15/20,77.0,-7.93,-14.42,73.09,15.43

In [7]:
ideal_df = weather_df.loc[((weather_df["Max Temp"]<=80) & (weather_df["Max Temp"]>70) & (weather_df["Wind Speed"]<10.00) & (weather_df["Cloudiness"]==0))]
ideal_df

,City_ID,City,Cloudiness,Country,Date,Humidity,Lat,Lng,Max Temp,Wind Speed
55,962367.0,Richards Bay,0.0,ZA,10/15/20,64.0,-28.78,32.04,73.74,9.37
64,1274899.0,Chākia,0.0,IN,10/15/20,70.0,26.42,85.05,79.39,2.62
91,2063042.0,Port Hedland,0.0,AU,10/15/20,73.0,-20.32,118.57,71.60,8.05
162,3369174.0,Calvinia,0.0,ZA,10/15/20,22.0,-31.47,19.78,71.29,3.60
203,53372.0,Oodweyne,0.0,SO,10/15/20,23.0,9.41,45.06,79.45,7.76
215,2109701.0,Auki,0.0,SB,10/15/20,84.0,-8.77,160.70,77.49,4.21
242,934649.0,Cap Malheureux,0.0,MU,10/15/20,74.0,-19.98,57.61,75.00,4.00
270,108410.0,Riyadh,0.0,SA,10/15/20,23.0,24.69,46.72,73.40,3.36
301,286987.0,Nizwá,0.0,OM,10/15/20,24.0,22.93,57.53,73.96,2.64
303,3832899.0,Viedma,0.0,AR,10/15/20,28.0,-40.81,-63.00,79.00,7.00
341,102527.0,Sakakah,0.0,SA,10/15/20,17.0,29.97,40.21,77.00,6.93
359,6620339.0,Karratha,0.0,AU,10/15/20,38.0,-20.74,116.85,74.82,9.24
380,2214432.0,Nālūt,0.0,LY,10/15/20,17.0,30.33,10.85,78.46,8.43
404,949683.0,Thabazimbi,0.0,ZA,10/15/20,33.0,-24.59,27.41,77.31,4.65
422,1266596.0,Khūtār,0.0,IN,10/15/20,60.0,28.20,80.28,75.72,4.21
444,1047660.0,Cuamba,0.0,MZ,10/15/20,48.0,-14.80,36.54,75.69,7.29
452,1162316.0,Yazman,0.0,PK,10/15/20,18.0,29.12,71.74,76.96,1.86
456,2065594.0,Mount Isa,0.0,AU,10/15/20,29.0,-20.73,139.50,77.00,8.05
492,1254709.0,Tezu,0.0,IN,10/15/20,58.0,27.92,96.17,76.59,3.38
500,285628.0,Hawalli,0.0,KW,10/15/20,37.0,29.28,48.00,71.60,5.82
538,3361142.0,Springbok,0.0,ZA,10/15/20,21.0,-29.66,17.89,72.18,5.64
594,2068110.0,Kununurra,0.0,AU,10/15/20,100.0,-15.77,128.73,73.40,7.36
612,934479.0,Grand Gaube,0.0,MU,10/15/20,74.0,-20.01,57.66,75.00,4.00

### Hotel Map
* Store into variable named `hotel_df`.
* Add a "Hotel Name" column to the DataFrame.
* Set parameters to search for hotels with 5000 meters.
* Hit the Google Places API for each city's coordinates.
* Store the first Hotel result into the DataFrame.
* Plot markers on top of the heatmap.

In [8]:
# Store into variable named hotel_df.

hotel_df = ideal_df[["City_ID", "City", "Cloudiness", "Country", "Date", "Humidity", "Lat", "Lng", "Max Temp", "Wind Speed"]]

# Add column for Hotel Name
hotel_df["Hotel Name"] = ""
hotel_df.head()

,City_ID,City,Cloudiness,Country,Date,Humidity,Lat,Lng,Max Temp,Wind Speed,Hotel Name
55,962367.0,Richards Bay,0.0,ZA,10/15/20,64.0,-28.78,32.04,73.74,9.37,
64,1274899.0,Chākia,0.0,IN,10/15/20,70.0,26.42,85.05,79.39,2.62,
91,2063042.0,Port Hedland,0.0,AU,10/15/20,73.0,-20.32,118.57,71.60,8.05,
162,3369174.0,Calvinia,0.0,ZA,10/15/20,22.0,-31.47,19.78,71.29,3.60,
203,53372.0,Oodweyne,0.0,SO,10/15/20,23.0,9.41,45.06,79.45,7.76,

In [9]:
# params dictionary to update each iteration
params = {
    "radius": 5000,
    "types": "lodging",
    "keyword": "Hotel",
    "key": g_key
}

# Use the lat/lng we recovered to identify airports
for index, row in hotel_df.iterrows():
    # get lat, lng from hotel_df
    lat = row["Lat"]
    lng = row["Lng"]

    # change location each iteration while leaving original params in place
    params["location"] = f"{lat},{lng}"

    # Use the search term: "Hotel" and our lat/lng
    base_url = "https://maps.googleapis.com/maps/api/place/nearbysearch/json"

    # make request and print url
    name_address = requests.get(base_url, params=params)
    
#     print the name_address url, avoid doing for public github repos in order to avoid exposing key
    #print(name_address.url)

    # convert to json
    name_address = name_address.json()
    #print(json.dumps(name_address, indent=4, sort_keys=True))

    # Since some data may be missing we incorporate a try-except to skip any that are missing a data point.
    try:
        hotel_df.loc[index, "Hotel Name"] = name_address["results"][0]["name"]
        #hotel_df.loc[index, "Airport Address"] = name_address["results"][0]["vicinity"]
        #hotel_df.loc[index, "Airport Rating"] = name_address["results"][0]["rating"]
    except (KeyError, IndexError):
        print("Missing field/result... skipping.")
hotel_df.info()

Missing field/result... skipping.
Missing field/result... skipping.
<class 'pandas.core.frame.DataFrame'>
Int64Index: 23 entries, 55 to 612
Data columns (total 11 columns):
 #   Column      Non-Null Count  Dtype
---  ------      --------------  -----
 0   City_ID     23 non-null     float64
 1   City        23 non-null     object
 2   Cloudiness  23 non-null     float64
 3   Country     23 non-null     object
 4   Date        23 non-null     object
 5   Humidity    23 non-null     float64
 6   Lat         23 non-null     float64
 7   Lng         23 non-null     float64
 8   Max Temp    23 non-null     float64
 9   Wind Speed  23 non-null     float64
 10  Hotel Name  23 non-null     object
dtypes: float64(7), object(4)
memory usage: 2.8+ KB

In [10]:
# Drop the city not found, sort by city name and reset index
hotel_df.sort_values(["City"], inplace=True)
hotel_df.reset_index(inplace =True)
hotel_df

,index,City_ID,City,Cloudiness,Country,Date,Humidity,Lat,Lng,Max Temp,Wind Speed,Hotel Name
0,215,2109701.0,Auki,0.0,SB,10/15/20,84.0,-8.77,160.70,77.49,4.21,Auki Lodge
1,162,3369174.0,Calvinia,0.0,ZA,10/15/20,22.0,-31.47,19.78,71.29,3.60,Calvinia Hotel by Country Hotels
2,242,934649.0,Cap Malheureux,0.0,MU,10/15/20,74.0,-19.98,57.61,75.00,4.00,Paradise Cove Boutique Hotel
3,64,1274899.0,Chākia,0.0,IN,10/15/20,70.0,26.42,85.05,79.39,2.62,SPOT ON 64941 Awasiya Subhash Hotel
4,444,1047660.0,Cuamba,0.0,MZ,10/15/20,48.0,-14.80,36.54,75.69,7.29,Daania Residence
5,612,934479.0,Grand Gaube,0.0,MU,10/15/20,74.0,-20.01,57.66,75.00,4.00,LUX Grand Gaube Resort & Villas
6,500,285628.0,Hawalli,0.0,KW,10/15/20,37.0,29.28,48.00,71.60,5.82,Crowne Plaza Kuwait al Thuraya City
7,359,6620339.0,Karratha,0.0,AU,10/15/20,38.0,-20.74,116.85,74.82,9.24,Karratha International Hotel
8,422,1266596.0,Khūtār,0.0,IN,10/15/20,60.0,28.20,80.28,75.72,4.21,
9,594,2068110.0,Kununurra,0.0,AU,10/15/20,100.0,-15.77,128.73,73.40,7.36,ibis Styles Kununurra
10,456,2065594.0,Mount Isa,0.0,AU,10/15/20,29.0,-20.73,139.50,77.00,8.05,Isa Hotel
11,301,286987.0,Nizwá,0.0,OM,10/15/20,24.0,22.93,57.53,73.96,2.64,Nizwa Residence Hotel Apartments
12,380,2214432.0,Nālūt,0.0,LY,10/15/20,17.0,30.33,10.85,78.46,8.43,
13,203,53372.0,Oodweyne,0.0,SO,10/15/20,23.0,9.41,45.06,79.45,7.76,Al shukri hotel
14,91,2063042.0,Port Hedland,0.0,AU,10/15/20,73.0,-20.32,118.57,71.60,8.05,The Esplanade Hotel
15,55,962367.0,Richards Bay,0.0,ZA,10/15/20,64.0,-28.78,32.04,73.74,9.37,BON Hotel Waterfront Richards Bay
16,270,108410.0,Riyadh,0.0,SA,10/15/20,23.0,24.69,46.72,73.40,3.36,Best Western Plus Fursan Hotel
17,341,102527.0,Sakakah,0.0,SA,10/15/20,17.0,29.97,40.21,77.00,6.93,Raoum Inn Hotel
18,538,3361142.0,Springbok,0.0,ZA,10/15/20,21.0,-29.66,17.89,72.18,5.64,Springbok Inn by Country Hotels
19,492,1254709.0,Tezu,0.0,IN,10/15/20,58.0,27.92,96.17,76.59,3.38,Capital O 66991 Hotel Highway
20,404,949683.0,Thabazimbi,0.0,ZA,10/15/20,33.0,-24.59,27.41,77.31,4.65,Maroela Guest Lodge
21,303,3832899.0,Viedma,0.0,AR,10/15/20,28.0,-40.81,-63.00,79.00,7.00,Hotel Austral Viedma
22,452,1162316.0,Yazman,0.0,PK,10/15/20,18.0,29.12,71.74,76.96,1.86,Royal Nawab Marriage Hall

In [11]:
# NOTE: Do not change any of the code in this cell

# Using the template add the hotel marks to the heatmap
info_box_template = """
<dl>
<dt>Name</dt><dd>{Hotel Name}</dd>
<dt>City</dt><dd>{City}</dd>
<dt>Country</dt><dd>{Country}</dd>
</dl>
"""
# Store the DataFrame Row
# NOTE: be sure to update with your DataFrame name
hotel_info = [info_box_template.format(**row) for index, row in hotel_df.iterrows()]
locations = hotel_df[["Lat", "Lng"]]

In [12]:
# Add marker layer ontop of heat map

figure_layout = {
    'width': '900px',
    'height': '600px',
    'border': '1px solid black',
    'padding': '1px',
    'margin': '0 auto 0 auto'
}
fig = gmaps.figure(layout=figure_layout,zoom_level=2,center=(15,25))

# Create hotel symbol layer
hotel_layer = gmaps.marker_layer(
    locations,info_box_content=[info_box_template.format(**row) for index, row in hotel_df.iterrows()]
)


# Add layer
fig.add_layer(heat_layer)
fig.add_layer(hotel_layer)

# Display figure
fig

Figure(layout=FigureLayout(border='1px solid black', height='600px', margin='0 auto 0 auto', padding='1px', wi…